version: '3'

volumes:
  pg_data_production:
  static_production:
  media_production:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      pg_data_production:/var/lib/postgresql/data
  backend:
    image: bar2les/kittygram_backend
    env_file: .env
    volumes:
      - static_production:/backend_static
      - media_production:/media
    depends_on:
      - db
  frontend:
    image: bar2les/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_production:/frontend_static
  gateway:
    image: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_production:/static/
      - media_production:/media/

